---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print message
      debug:
        msg: "{{ item }}"
      loop:
        - "Artur"
        - "Snusz"
        - "Piotr"
         